apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "team-c"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ajay-Chidambaram/team-c
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
