apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "temp-table"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ajay-Chidambaram/temp-dir
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
