apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "test-name-bucket"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ajay-Chidambaram/summa-oru-test
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
