apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "test-bucket-123"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/"Ajay-Chidambaram"/"cncf-demo-1"
    targetRevision: HEAD
    path: /manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
