apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "test-pr-1"
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {"host":"github.com","owner":"Ajay-Chidambaram","repo":"cncf-demo-3"}
    targetRevision: HEAD
    path: /manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
